# Generated by Django 2.2.14 on 2020-07-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvin', '0002_auto_20200708_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='marvin/model_images/projects'),
        ),
    ]
